### ISSUE TITLE
Error trying to run make on WSL for Linux (Ubuntu 18.04)

### ISSUE THREAD

**Issue by agile-x86** [tihmstar/libinsn#1]
I'm trying to run `make` after cloning the project and running `./autogen.sh` , but I keep getting this error when doing so: 

`root@Bennys-Laptop:~/libinsn# make
(CDPATH="${ZSH_VERSION+.}:" && cd . && /bin/bash /home/benny/libinsn/missing autoheader)
rm -f stamp-h1
touch config.h.in
cd . && /bin/bash ./config.status config.h
config.status: creating config.h
config.status: config.h is unchanged
make  all-recursive
make[1]: Entering directory '/home/benny/libinsn'
Making all in libinsn
make[2]: Entering directory '/home/benny/libinsn/libinsn'
/bin/bash ../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I..  -I../include -I../include/libinsn -I/usr/local/include   -g -O2 -std=c++14 -O3 -D EXPECTIONNAME=INSNexception -MT libinsn_la-insn_decode.lo -MD -MP -MF .deps/libinsn_la-insn_decode.Tpo -c -o libinsn_la-insn_decode.lo `test -f 'insn_decode.cpp' || echo './'`insn_decode.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I.. -I../include -I../include/libinsn -I/usr/local/include -g -O2 -std=c++14 -O3 -D EXPECTIONNAME=INSNexception -MT libinsn_la-insn_decode.lo -MD -MP -MF .deps/libinsn_la-insn_decode.Tpo -c insn_decode.cpp  -fPIC -DPIC -o .libs/libinsn_la-insn_decode.o
insn_decode.cpp:142:2: warning: #warning TODO incomplete function implementation! [-Wcpp]
 #warning TODO incomplete function implementation!
  ^~~~~~~
insn_decode.cpp:185:2: warning: #warning TODO redo this! currently only recognises STR (immediate) [-Wcpp]
 #warning TODO redo this! currently only recognises STR (immediate)
  ^~~~~~~
insn_decode.cpp:652:2: warning: #warning TODO rewrite this! currently only unsigned offset supported [-Wcpp]
 #warning TODO rewrite this! currently only unsigned offset supported
  ^~~~~~~
insn_decode.cpp: In constructor ‘constexpr decoder_stage1::decoder_stage1()’:
insn_decode.cpp:419:155: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
 e1_insn[0b00101000 | SET_BITS(i & 1,7) | SET_BITS(i >> 1,0)] = {false, .next_stage_decoder = special_decoders_stp_ldp};
                                                                                                                      ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:422:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b11010110] = {false, .next_stage_decoder = special_decoders_0b11010110};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:423:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b01111000] = {false, .next_stage_decoder = special_decoders_0b01111000};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:424:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b01110010] = {false, .next_stage_decoder = special_decoders_0b01110010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:425:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b11110010] = {false, .next_stage_decoder = special_decoders_0b11110010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:426:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b00110010] = {false, .next_stage_decoder = special_decoders_0b00110010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:427:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b10110010] = {false, .next_stage_decoder = special_decoders_0b10110010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:428:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b10001000] = {false, .next_stage_decoder = special_decoders_0b10001000};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:429:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b11001000] = {false, .next_stage_decoder = special_decoders_0b11001000};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:430:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b00111000] = {false, .next_stage_decoder = special_decoders_0b00111000};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:431:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b10111000] = {false, .next_stage_decoder = special_decoders_0b10111000};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:432:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b11111000] = {false, .next_stage_decoder = special_decoders_0b11111000};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:433:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b10111000] = {false, .next_stage_decoder = special_decoders_0b01010010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:434:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b11111000] = {false, .next_stage_decoder = special_decoders_0b11010010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:435:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b01010100] = {false, .next_stage_decoder = special_decoders_0b01010100};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:436:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b11010101] = {false, .next_stage_decoder = special_decoders_0b11010101};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:437:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b00010010] = {false, .next_stage_decoder = special_decoders_0b00010010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:438:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b10010010] = {false, .next_stage_decoder = special_decoders_0b10010010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:439:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b00011010] = {false, .next_stage_decoder = special_decoders_0b00011010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:440:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b10011010] = {false, .next_stage_decoder = special_decoders_0b10011010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:441:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b01111010] = {false, .next_stage_decoder = special_decoders_0b01111010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:442:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b11111010] = {false, .next_stage_decoder = special_decoders_0b11111010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:443:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b00011011] = {false, .next_stage_decoder = special_decoders_0b00011011};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:444:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b10011011] = {false, .next_stage_decoder = special_decoders_0b10011011};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp:445:93: error: no match for ‘operator=’ (operand types are ‘decoder_val’ and ‘<brace-enclosed initializer list>’)
         _stage1_insn[0b11011010] = {false, .next_stage_decoder = special_decoders_0b11011010};
                                                                                             ^
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(const decoder_val&)
 struct decoder_val{
        ^~~~~~~~~~~
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘const decoder_val&’
insn_decode.cpp:389:8: note: candidate: constexpr decoder_val& decoder_val::operator=(decoder_val&&)
insn_decode.cpp:389:8: note:   no known conversion for argument 1 from ‘<brace-enclosed initializer list>’ to ‘decoder_val&&’
insn_decode.cpp: At global scope:
insn_decode.cpp:116:67: warning: always_inline function might not be inlinable [-Wattributes]
 __attribute__((always_inline)) static std::pair<int64_t, int64_t> DecodeBitMasks(uint64_t immN, uint8_t imms, uint8_t immr, bool immediate){
                                                                   ^~~~~~~~~~~~~~
insn_decode.cpp:74:48: warning: always_inline function might not be inlinable [-Wattributes]
 __attribute__((always_inline)) static uint64_t ROR(uint64_t x, int shift, int len){
                                                ^~~
insn_decode.cpp:65:48: warning: always_inline function might not be inlinable [-Wattributes]
 __attribute__((always_inline)) static uint64_t ones(uint64_t n){
                                                ^~~~
insn_decode.cpp:56:48: warning: always_inline function might not be inlinable [-Wattributes]
 __attribute__((always_inline)) static uint64_t replicate(uint64_t val, int bits){
                                                ^~~~~~~~~
insn_decode.cpp:48:43: warning: always_inline function might not be inlinable [-Wattributes]
 __attribute__((always_inline)) static int lowestSetBit(uint64_t x){
                                           ^~~~~~~~~~~~
insn_decode.cpp:40:43: warning: always_inline function might not be inlinable [-Wattributes]
 __attribute__((always_inline)) static int highestSetBit(uint64_t x){
                                           ^~~~~~~~~~~~~
insn_decode.cpp:33:47: warning: always_inline function might not be inlinable [-Wattributes]
 __attribute__((always_inline)) static int64_t signExtend64(uint64_t v, int vSize){
                                               ^~~~~~~~~~~~
Makefile:458: recipe for target 'libinsn_la-insn_decode.lo' failed
make[2]: *** [libinsn_la-insn_decode.lo] Error 1
make[2]: Leaving directory '/home/benny/libinsn/libinsn'
Makefile:469: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/benny/libinsn'
Makefile:378: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by djeraseit** [comment]
make files on Ubuntu linux
https://pastebin.com/n83qRwfY

**Comment by tihmstar** [comment]
Should be fixed in c586405d63e9c8634dbc35c92046faefa4f6fa4f
Also for more info refer to issue https://github.com/tihmstar/libinsn/issues/3
