### ISSUE TITLE
lots of errors surrounding ‘loc_t’ when attempting to compile on Ubuntu 20.04

### ISSUE THREAD

**Issue by DanTheMann15** [tihmstar/libinsn#3]
**Compiler Error**
File(s): libinsn/vsegment.cpp - include/libinsn/vsegment.hpp - include/libinsn/insn.hpp
Line(s): (too many lines affected to list here, please see output.txt)
Error(s): (too many errors to list here, please see output.txt)

**libinsn version**
master-git (9725a0d)

**Operating System and Compiler**

System: Ubuntu 20.04 LTS (x86_64) Desktop
Compiler: GNU Compiler Collection (GCC)
Target: x86_64-linux-gnu

parameters passed to configure: `./autogen.sh --enable-static --disable-shared`

full console logs: [output.txt](https://github.com/tihmstar/libinsn/files/4992377/output.txt)

**Comment by tihmstar** [comment]
So there is two issues with compiling on Ubuntu.
The loc_t is fixed in c586405d63e9c8634dbc35c92046faefa4f6fa4f
The other problem is that if your gcc is too old, you'll run into a variant of this: https://twitter.com/tihmstar/status/1290581257651453953

I recommend installing clang `apt-get install clang` and before you run `./autogen.sh` run this:
```
export CC=clang
export CXX=clang++
```

**Comment by DanTheMann15** [comment]
ah i see... the version that goes with ubuntu 20.04 appears to be version 9.3.0, and the latest is 10.2.0.

i'll go ahead and see what i can do about running this through clang, and if need be i can try compiling it.
i am unsure however if i could get this up on windows, i'll play with it later though.

i'll let you know how it goes, thanks!

**Comment by DanTheMann15** [comment]
it compiles fine on ubuntu now.

however when i attempt to compile this on Windows i get this:

`vsegment.cpp: In member function 'tihmstar::libinsn::loc_t tihmstar::libinsn::vsegment::memmem(const void*, size_t, tihmstar::libinsn::loc_t)':
vsegment.cpp:48:24: error: '::memmem' has not been declared; did you mean 'memset'?
   48 |     if ((rt = (loc_t)::memmem(_buf+startOffset, _size-startOffset, little, little_len))) {
      |                        ^~~~~~
      |                        memset
`

full log here: [output.txt](https://github.com/tihmstar/libinsn/files/5092336/output.txt)


this probably should be an issue of it's own, clang on msys2 doesn't support the -fPIC flag so gcc seems to be the only option, but at least msys2 is great at updating their packages, so the gcc they provide is the latest 10.2.0.

**Comment by tihmstar** [comment]
Weird, so **memmem** should be defined in `string.h` (https://man7.org/linux/man-pages/man3/memmem.3.html)
and the `::` prefix tells it to use the global memmem function, rather than the one in `vsegment` (otherwise i'd be a recursive call)

Maybe you need to define `#define _GNU_SOURCE` before including `string.h` ?

**Comment by DanTheMann15** [comment]
gave that a shot, didn't work, i could try to use just the headers from glibc, but the library itself isn't there should it need to be linked, and using headers that aren't made for windows could have problems with the program.

i could try building it with cygwin, but it'll require the cygwin1.dll, unless i compile it's POSIX Emulation Library statically, if i can that is.

 as far as i know, memmem is part of the [glibc](https://www.gnu.org/software/libc/) library and it doesn't support windows. (not sure why though.)
i did however, through a google search found this https://gist.github.com/foxik384/496928d2785e9007d2b838cfa6e019ee
and this: https://stackoverflow.com/questions/52988769/writing-own-memmem-for-windows

i am not sure how this would work though, you could give it a shot.

**Comment by haen7** [comment]
Hi,
`memmem()` is not available in windows. you should add it manually. here is the code I used to build libinsn on mingw:
https://searchcode.com/codesearch/raw/18139875/. 

just add this to `vsegment.cpp`

```c
#ifdef _WIN32
void *memmem (const void *haystack, size_t haystack_len, const void *needle,size_t needle_len)
{
  const char *begin;
  const char *const last_possible
    = (const char *) haystack + haystack_len - needle_len;

  if (needle_len == 0)
    /* The first occurrence of the empty string is deemed to occur at
       the beginning of the string.  */
    return (void *) haystack;

  /* Sanity check, otherwise the loop might search through the whole
     memory.  */
  if (__builtin_expect (haystack_len < needle_len, 0))
    return NULL;

  for (begin = (const char *) haystack; begin <= last_possible; ++begin)
    if (begin[0] == ((const char *) needle)[0] &&
	!memcmp ((const void *) &begin[1],
		 (const void *) ((const char *) needle + 1),
		 needle_len - 1))
      return (void *) begin;

  return NULL;
}
#endif
```
