### ISSUE TITLE
error when trying to compile the latest build of libinsn on Ubuntu 20.04

### ISSUE THREAD

**Issue by iFred09** [tihmstar/libinsn#5]
hi,

I'm trying to compile libinsn for compile the new version of liboffsetfinder64.

When I launch the compilation, I have this error.
Someone can help me please?

Thanks,
iFred09
![Capture d’écran de 2020-12-25 22-22-46](https://user-images.githubusercontent.com/22419166/103142244-654c3f80-4700-11eb-81a2-b486d6e7cc44.png)

**Comment by NoaHimesaka1873** [comment]
Using clang works for me.

**Comment by dony71** [comment]
how to use clang?

**Comment by hellisabove** [comment]
export CC=clang;export CXX=clang++

**Comment by tihmstar** [comment]
clang needs to be used. added this to autotools in https://github.com/tihmstar/libinsn/commit/dc5e37d6b1e28a6c8fc157a37d75737cf681d520
